headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "D:\\problem-tracker\\functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]

[build]
publish = "D:\\problem-tracker\\frontend"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build step needed for this static site'"
functions = "D:\\problem-tracker\\functions"

[build.environment]
NODE_VERSION = "18.0.0"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]